version: "2"
services:

  postgres:
    image: postgres:9.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=TCrGaanoC2s7gT
    ports:
      - 5432:5432

  zookeeper:
    container_name: zookeeper
    image: znly/zookeeper:3.4.8
    links:
      - kafka:kafka
    environment:
      - ZOO_ID=1
      - ZOO_SERVERS=zookeeper
    ports:
      - 2181:2181

  overlord:
    build: ./druid
    command:
      - overlord
    ports:
      - 8090:8090

  coordinator:
    build: ./druid
    command:
      - coordinator
    ports:
      - 8081:8081

  middlemanager:
    build: ./druid
    command:
      - middleManager

  historical:
    build: ./druid
    command:
      - historical
    ports:
      - 8083:8083

  broker:
    build: ./druid
    environment:
      - DRUID_XMX=128m
      - DRUID_XMS=128m
      - DRUID_MAXNEWSIZE=128m
      - DRUID_NEWSIZE=128m
    command:
      - broker
    ports:
      - 8082:8082

  kafka:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=10.200.10.1:2181
      - KAFKA_ADVERTISED_HOST_NAME=10.200.10.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  tranquilitykafka:
    build: ./tranquility-kafka
